# Generated by Django 4.1 on 2022-09-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_profile_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
