# Generated by Django 4.1 on 2022-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.CharField(choices=[('1', 'Tequila'), ('2', 'Vodka'), ('3', 'Rum'), ('4', 'Lemon'), ('5', 'Coke')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
