# Generated by Django 4.1 on 2022-09-06 18:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_drink_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Tequila'), ('2', 'Vodka'), ('3', 'Rum'), ('4', 'Lemon'), ('5', 'Coke')], max_length=10),
        ),
    ]
