# Generated by Django 4.0.6 on 2022-09-06 18:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_drink_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Tequila'), ('2', 'Vodka'), ('3', 'Rum'), ('4', 'Lemon'), ('5', 'Coke')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
