# Generated by Django 4.1 on 2022-09-07 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_drink_favorites_drink_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
