# Generated by Django 4.1 on 2022-09-07 22:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_drink_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Brandy'), ('2', 'Gin'), ('3', 'Rum'), ('4', 'Tequila'), ('5', 'Vodka'), ('6', 'Whiskey'), ('7', 'Vodka'), ('8', 'Absinthe'), ('9', 'Amaretto'), ('10', 'Aperol'), ('11', 'Baileys'), ('12', 'Blue Curacao'), ('13', 'Campari'), ('14', 'Chambord'), ('15', 'Chartreause Green'), ('16', 'Chartreause Yellow'), ('17', 'Cointreau'), ('18', 'Creme de Cacao'), ('19', 'Creme de Cassis'), ('20', 'Creme de Menthe'), ('21', 'Frangelico'), ('22', 'Jagermeister'), ('23', 'Kahlua'), ('24', 'Midori'), ('25', 'Triple Sec'), ('26', 'Club Soda'), ('27', 'Cola'), ('28', 'Cranberry Juice'), ('29', 'Cream'), ('30', 'Diet Cola'), ('31', 'Energy Drink'), ('32', 'Ginger Ale'), ('33', 'Ginger Beer'), ('34', 'Grapefruit Juice'), ('35', 'Lemon Juice'), ('36', 'Lemon/Lime Soda'), ('37', 'Lime Juice'), ('38', 'Orange Juice'), ('39', 'Simple Syrup'), ('40', 'Sour Mix'), ('41', 'Tomato Juice'), ('42', 'Tonic')], max_length=50),
        ),
    ]
