# Generated by Django 4.1 on 2022-09-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_drink_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('1', '🍹'), ('2', '🍹🍹'), ('3', '🍹🍹🍹'), ('4', '🍹🍹🍹🍹'), ('5', '🍹🍹🍹🍹🍹')], max_length=1)),
                ('review', models.TextField(max_length=300)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.drink')),
            ],
        ),
    ]
