# Generated by Django 4.1 on 2022-09-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '🍹'), ('2', '🍹🍹'), ('3', '🍹🍹🍹'), ('4', '🍹🍹🍹🍹'), ('5', '🍹🍹🍹🍹🍹')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
