# Generated by Django 4.1 on 2022-09-08 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0017_alter_review_rating_alter_review_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Brandy'), ('2', 'Gin'), ('3', 'Rum'), ('4', 'Tequila'), ('5', 'Vodka'), ('6', 'Whiskey'), ('7', 'Whiskey Scotch'), ('8', 'Absinthe'), ('9', 'Amaretto'), ('10', 'Aperol'), ('11', 'Baileys'), ('12', 'Blue Curacao'), ('13', 'Campari'), ('14', 'Chambord'), ('15', 'Chartreause Green'), ('16', 'Chartreause Yellow'), ('17', 'Cointreau'), ('18', 'Creme de Cacao'), ('19', 'Creme de Cassis'), ('20', 'Creme de Menthe'), ('21', 'Frangelico'), ('22', 'Jagermeister'), ('23', 'Kahlua'), ('24', 'Midori'), ('25', 'Triple Sec'), ('43', 'Vermouth Dry'), ('44', 'Vermouth Sweet'), ('26', 'Club Soda'), ('27', 'Cola'), ('28', 'Cranberry Juice'), ('29', 'Cream'), ('30', 'Diet Cola'), ('31', 'Energy Drink'), ('32', 'Ginger Ale'), ('33', 'Ginger Beer'), ('34', 'Grapefruit Juice'), ('35', 'Lemon Juice'), ('36', 'Lemon/Lime Soda'), ('37', 'Lime Juice'), ('38', 'Orange Juice'), ('39', 'Simple Syrup'), ('40', 'Sour Mix'), ('41', 'Tomato Juice'), ('42', 'Tonic')], max_length=50),
        ),
    ]
